"""scripts/lib/nginx-socket-listens: which IPv6 sockets home-warden.socket adds
for the served conf, and the drop-ins that add them (#156).

nginx only adopts an inherited socket whose address a `listen` names exactly,
so the sockets systemd opens and the listens in the conf must match.
"""

import re
import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
LIB = REPO / "scripts" / "lib" / "nginx-socket-listens"
SOCKET_UNIT = REPO / "etc" / "systemd" / "home-warden.socket"
DUAL_STACK = "listen 443 ssl;\nlisten [::]:443 ssl;\nlisten [::]:80;\n"
HEADER = "# GENERATED by home-warden scripts/setup-service -- do not edit."


def test_bare_ipv6_listen_means_port_80() -> None:
    ports, _, rc = _ports("listen [::];\nlisten [::] default_server;\n")
    assert (ports, rc) == (["80"], 0)


def test_ipv4_only_conf_needs_no_ipv6_socket() -> None:
    ports, _, rc = _ports("listen 80;\nlisten 443 ssl default_server;\nlisten 0.0.0.0:443 ssl;\n")
    assert (ports, rc) == ([], 0)


def test_ipv6_listens_on_80_and_443_are_reported_once_each_in_port_order() -> None:
    dump = (
        "server {\n"
        "    listen 443 ssl default_server;\n"
        "    listen [::]:443 ssl default_server;\n"
        "}\n"
        "server {\n"
        "    listen [::]:443 ssl;\n"
        "}\n"
        "server {\n"
        "    listen 80;\n"
        "    listen [::]:80;\n"
        "}\n"
    )
    ports, _, rc = _ports(dump)
    assert (ports, rc) == (["80", "443"], 0)


def test_ipv6_listens_split_across_lines_or_after_a_brace_are_found() -> None:
    ports, _, rc = _ports("server { listen [::]:80; }\nserver {\n    listen [::]:443\n        ssl default_server;\n}\n")
    assert (ports, rc) == (["80", "443"], 0)


def test_ipv6only_off_is_refused() -> None:
    ports, stderr, rc = _ports("listen [::]:443 ssl ipv6only=off;\nlisten [::]:80;\n")
    assert rc == 1
    assert ports == ["80"]
    assert "listen [::]:443 sets ipv6only=off" in stderr


def test_listens_on_other_ports_and_addresses_are_ignored() -> None:
    dump = (
        "listen [::]:8443 ssl;\n"
        "listen [::1]:443 ssl;\n"
        "listen 127.0.0.1:8080;\n"
        "# listen [::]:80;\n"
        "    listen_extra [::]:80;\n"
    )
    ports, _, rc = _ports(dump)
    assert (ports, rc) == ([], 0)


def test_quoted_hash_before_a_listen_does_not_hide_it() -> None:
    ports, _, rc = _ports('return 200 "a # b"; listen [::]:443 ssl;\n')
    assert (ports, rc) == (["443"], 0)


def test_service_dropin_fds_start_after_the_socket_units_own_listeners() -> None:
    base = len(re.findall(r"^ListenStream=", SOCKET_UNIT.read_text(), re.MULTILINE))
    service = _render("render_ipv6_service_dropin", "80", "443")
    assert service[-1] == "Environment=NGINX=" + ":".join(str(fd) for fd in range(3, 3 + base + 2)) + ";"


def test_service_dropin_lists_one_fd_per_socket() -> None:
    assert _render("render_ipv6_service_dropin", "443") == [HEADER, "[Service]", "Environment=NGINX=3:4:5;"]
    assert _render("render_ipv6_service_dropin", "80", "443") == [HEADER, "[Service]", "Environment=NGINX=3:4:5:6;"]


def test_socket_dropin_adds_ipv6_only_listeners() -> None:
    assert _render("render_ipv6_socket_dropin", "80", "443") == [
        HEADER,
        "[Socket]",
        "BindIPv6Only=ipv6-only",
        "ListenStream=[::]:80",
        "ListenStream=[::]:443",
    ]


def test_sync_leaves_matching_dropins_alone(tmp_path: Path) -> None:
    service, socket = tmp_path / "service.conf", tmp_path / "socket.conf"
    assert _sync(DUAL_STACK, service, socket) == ("changed", 0)
    assert _sync(DUAL_STACK, service, socket) == ("", 0)


def test_sync_refuses_ipv6only_off_without_touching_the_dropins(tmp_path: Path) -> None:
    service, socket = tmp_path / "service.conf", tmp_path / "socket.conf"
    assert _sync("listen [::]:443 ssl ipv6only=off;\n", service, socket)[1] == 1
    assert not service.exists() and not socket.exists()


def test_sync_removes_generated_dropins_but_not_hand_written_ones(tmp_path: Path) -> None:
    service, socket = tmp_path / "service.conf", tmp_path / "socket.conf"
    _sync(DUAL_STACK, service, socket)
    socket.write_text("[Socket]\nBacklog=512\n")
    assert _sync("listen 443 ssl;\n", service, socket) == ("changed", 0)
    assert not service.exists()
    assert socket.read_text() == "[Socket]\nBacklog=512\n"
    assert _sync("listen 443 ssl;\n", service, socket) == ("", 0)


def test_sync_writes_both_dropins_for_new_ipv6_listens(tmp_path: Path) -> None:
    service, socket = tmp_path / "service.conf", tmp_path / "socket.conf"
    assert _sync(DUAL_STACK, service, socket) == ("changed", 0)
    assert service.read_text().splitlines()[-1] == "Environment=NGINX=3:4:5:6;"
    assert socket.read_text().splitlines()[-2:] == ["ListenStream=[::]:80", "ListenStream=[::]:443"]
    assert _sync("listen [::]:443 ssl;\n", service, socket) == ("changed", 0)
    assert service.read_text().splitlines()[-1] == "Environment=NGINX=3:4:5;"


def _ports(dump: str) -> tuple[list[str], str, int]:
    result = subprocess.run(
        ["bash", "-c", 'source "$1"; shift; resolve_nginx_ipv6_listen_ports "$@"', "bash", str(LIB), dump],
        capture_output=True,
        check=False,
        text=True,
        timeout=10,
    )
    return result.stdout.split(), result.stderr, result.returncode


def _render(function: str, *ports: str) -> list[str]:
    result = subprocess.run(
        ["bash", "-c", f'source "$1"; shift; {function} "$@"', "bash", str(LIB), *ports],
        capture_output=True,
        check=True,
        text=True,
        timeout=10,
    )
    return result.stdout.splitlines()


def _sync(dump: str, service: Path, socket: Path) -> tuple[str, int]:
    script = (
        'source "$1"; shift; '
        'install_generated_dropin() { printf "%s\\n" "$1" >"$2"; }; '
        'remove_generated_dropin() { rm -f "$1"; }; '
        'sync_ipv6_socket_dropins "$@"'
    )
    result = subprocess.run(
        ["bash", "-c", script, "bash", str(LIB), dump, str(service), str(socket)],
        capture_output=True,
        check=False,
        text=True,
        timeout=10,
    )
    return result.stdout.strip(), result.returncode
