"""scripts/lib/nginx-socket-listens: which IPv6 sockets home-warden.socket adds
for the served conf, and the drop-ins that add them (#156).

nginx only adopts an inherited socket whose address a `listen` names exactly,
so the sockets systemd opens and the listens in the conf must match.
"""

import subprocess
from pathlib import Path

LIB = Path(__file__).resolve().parents[2] / "scripts" / "lib" / "nginx-socket-listens"
HEADER = "# GENERATED by home-warden scripts/setup-service -- do not edit."


def test_bare_ipv6_listen_means_port_80() -> None:
    ports, _, rc = _ports("listen [::];\nlisten [::] default_server;\n")
    assert (ports, rc) == (["80"], 0)


def test_ipv4_only_conf_needs_no_ipv6_socket() -> None:
    ports, _, rc = _ports("listen 80;\nlisten 443 ssl default_server;\nlisten 0.0.0.0:443 ssl;\n")
    assert (ports, rc) == ([], 0)


def test_ipv6_listens_on_80_and_443_are_reported_once_each_in_port_order() -> None:
    dump = (
        "server {\n"
        "    listen 443 ssl default_server;\n"
        "    listen [::]:443 ssl default_server;\n"
        "}\n"
        "server {\n"
        "    listen [::]:443 ssl;\n"
        "}\n"
        "server {\n"
        "    listen 80;\n"
        "    listen [::]:80;\n"
        "}\n"
    )
    ports, _, rc = _ports(dump)
    assert (ports, rc) == (["80", "443"], 0)


def test_ipv6only_off_is_refused() -> None:
    ports, stderr, rc = _ports("listen [::]:443 ssl ipv6only=off;\nlisten [::]:80;\n")
    assert rc == 1
    assert ports == ["80"]
    assert "listen [::]:443 sets ipv6only=off" in stderr


def test_listens_on_other_ports_and_addresses_are_ignored() -> None:
    dump = (
        "listen [::]:8443 ssl;\n"
        "listen [::1]:443 ssl;\n"
        "listen 127.0.0.1:8080;\n"
        "# listen [::]:80;\n"
        "    listen_extra [::]:80;\n"
    )
    ports, _, rc = _ports(dump)
    assert (ports, rc) == ([], 0)


def test_service_dropin_lists_one_fd_per_socket() -> None:
    assert _render("render_ipv6_service_dropin", "443") == [HEADER, "[Service]", "Environment=NGINX=3:4:5;"]
    assert _render("render_ipv6_service_dropin", "80", "443") == [HEADER, "[Service]", "Environment=NGINX=3:4:5:6;"]


def test_socket_dropin_adds_ipv6_only_listeners() -> None:
    assert _render("render_ipv6_socket_dropin", "80", "443") == [
        HEADER,
        "[Socket]",
        "BindIPv6Only=ipv6-only",
        "ListenStream=[::]:80",
        "ListenStream=[::]:443",
    ]


def _ports(dump: str) -> tuple[list[str], str, int]:
    result = subprocess.run(
        ["bash", "-c", 'source "$1"; shift; resolve_nginx_ipv6_listen_ports "$@"', "bash", str(LIB), dump],
        capture_output=True,
        check=False,
        text=True,
        timeout=10,
    )
    return result.stdout.split(), result.stderr, result.returncode


def _render(function: str, *ports: str) -> list[str]:
    result = subprocess.run(
        ["bash", "-c", f'source "$1"; shift; {function} "$@"', "bash", str(LIB), *ports],
        capture_output=True,
        check=True,
        text=True,
        timeout=10,
    )
    return result.stdout.splitlines()
