"""Convert tinydns-format zone data (thehcma/home's `dns/data`) into
PowerDNS GeoIP-backend zone YAML, per the record mapping the-hcma/home#16
already worked out against the real file. See the-hcma/home-warden#108.

Implements exactly the tinydns line types #16 identified as actually used
-- SOA (`Z`), NS with optional glue A (`&`), A+PTR (`=`), A-only (`+`),
TXT (`'`), CNAME (`C`), and SRV via the generic record line (`:` type
`33`, octal-escaped wire rdata) -- and fails loudly on any other line
type rather than silently dropping data.

Each RR is placed under the longest-matching zone apex from the SOA (`Z`)
lines found in the file (mirrors app.catalog_checks.candidate_zone_names'
apex-first walk, but against a known, closed set of zones rather than a
live API).
"""

from __future__ import annotations

from dataclasses import dataclass, field

DEFAULT_TTL = 3600
GENERIC_SRV_TYPE = "33"


@dataclass
class ParsedRecord:
    owner: str
    rtype: str  # "soa" | "ns" | "a" | "ptr" | "cname" | "txt" | "srv"
    content: str
    ttl: int | None = None


@dataclass
class Zone:
    apex: str
    ttl: int
    # owner -> rtype -> list[content] (soa/cname are single-valued but
    # still stored as a one-element list; render_zones_yaml unwraps them).
    records: dict[str, dict[str, list[str]]] = field(default_factory=dict)


def bucket_into_zones(records: list[ParsedRecord], zone_apexes: list[str]) -> dict[str, Zone]:
    """Group parsed records under the longest-matching zone apex.

    `zone_apexes` must already be known (from the file's own SOA lines) --
    unlike app.catalog_checks.candidate_zone_names, this never probes an
    external source; it picks the best of a closed, given set. A record
    whose owner matches no known apex is an error: silently dropping it
    would produce a zone file missing data the source file clearly
    intended to serve.
    """
    zones = {apex: Zone(apex=apex, ttl=DEFAULT_TTL) for apex in zone_apexes}
    sorted_apexes = sorted(zone_apexes, key=len, reverse=True)

    for rec in records:
        apex = _longest_matching_apex(rec.owner, sorted_apexes)
        if apex is None:
            raise ValueError(f"no zone apex matches owner {rec.owner!r} (known zones: {zone_apexes})")
        owner_records = zones[apex].records.setdefault(rec.owner, {})
        owner_records.setdefault(rec.rtype, []).append(rec.content)
        if rec.rtype == "soa" and rec.ttl is not None:
            zones[apex].ttl = rec.ttl

    return zones


def parse_tinydns_data(text: str) -> list[ParsedRecord]:
    """Parse tinydns data-file text into a flat list of records, in file
    order. Raises ValueError on any unrecognized line type/shape -- see
    module docstring for why this stays narrow rather than implementing
    the full tinydns-data(5) grammar.
    """
    records: list[ParsedRecord] = []
    for lineno, raw_line in enumerate(text.splitlines(), start=1):
        if not raw_line or raw_line.startswith("#"):
            continue
        try:
            records.extend(_parse_line(raw_line))
        except ValueError as e:
            raise ValueError(f"line {lineno}: {e}") from e
    return records


def render_pdns_conf(zones_yaml_path: str) -> str:
    """Render the pdns.conf snippet pointing at `zones_yaml_path`, per
    the-hcma/home#16's already-validated design: the authoritative
    `pdns_server` listens only on loopback:853 (never the public/LAN
    :53), plain `records:` only (no MaxMind/geo expansions --
    `geoip-database-files=` stays empty), and the *recursor* (unchanged,
    hand-maintained `dns/recursor.conf`) is what actually answers :53,
    forwarding queries for these authoritative zones to loopback:853.
    """
    return (
        "# GENERATED by dns-tinydns-convert (the-hcma/home-warden#108) -- do not edit.\n"
        "launch=geoip\n"
        f"geoip-zones-file={zones_yaml_path}\n"
        "geoip-database-files=\n"
        "log-dns-details=yes\n"
        "log-dns-queries=yes\n"
        "loglevel=5\n"
        "local-address=127.0.0.1\n"
        "local-port=853\n"
    )


def render_zones_yaml(zones: dict[str, Zone]) -> str:
    """Render the PowerDNS GeoIP backend's zones.yml text (a top-level
    `domains:` list, one entry per zone) -- imported lazily so a caller
    that only needs parsing/bucketing (e.g. the sqlite-backend validator)
    doesn't need PyYAML installed.
    """
    import yaml

    domains = []
    for apex in sorted(zones):
        zone = zones[apex]
        owner_map: dict[str, dict[str, object]] = {}
        for owner in sorted(zone.records):
            type_map: dict[str, object] = {}
            for rtype in sorted(zone.records[owner]):
                values = zone.records[owner][rtype]
                type_map[rtype] = values[0] if rtype in ("soa", "cname") else values
            owner_map[owner] = type_map
        domains.append({"domain": apex, "ttl": zone.ttl, "records": owner_map})

    header = (
        "# GENERATED by dns-tinydns-convert (the-hcma/home-warden#108) -- do not edit.\n"
        "# Edit this file directly for ongoing changes (it is the source of truth going\n"
        "# forward, per #108); only the initial migration ran the converter.\n"
    )
    return header + yaml.safe_dump({"domains": domains}, sort_keys=False, default_flow_style=False)


def zone_apexes_from_records(records: list[ParsedRecord]) -> list[str]:
    """SOA (`Z`) records define the zones -- collect their owners, in the
    order first seen, so bucketing has a closed set to match against.
    """
    return [rec.owner for rec in records if rec.rtype == "soa"]


def _decode_srv_rdata(field_text: str) -> str:
    data = _decode_tinydns_escapes(field_text)
    if len(data) < 7:
        raise ValueError(f"SRV rdata too short ({len(data)} bytes)")
    priority = (data[0] << 8) | data[1]
    weight = (data[2] << 8) | data[3]
    port = (data[4] << 8) | data[5]
    target, _ = _decode_wire_name(data, 6)
    return f"{priority} {weight} {port} {target}"


def _decode_tinydns_escapes(field_text: str) -> bytes:
    """Decode tinydns's `\\NNN` (exactly 3 octal digits) byte escapes.
    Any other character is its own literal byte -- matches tinydns-data's
    own escaping convention for TXT content and generic-record rdata.
    """
    out = bytearray()
    i, n = 0, len(field_text)
    while i < n:
        if field_text[i] == "\\" and i + 4 <= n and all(c in "01234567" for c in field_text[i + 1 : i + 4]):
            out.append(int(field_text[i + 1 : i + 4], 8))
            i += 4
        else:
            out.append(ord(field_text[i]) & 0xFF)
            i += 1
    return bytes(out)


def _decode_wire_name(data: bytes, offset: int) -> tuple[str, int]:
    """Decode a DNS wire-format name (length-prefixed labels, zero-length
    root label terminator; no compression pointers -- tinydns's generic
    records never emit those) starting at `offset`. Returns (name, the
    offset just past the terminating zero byte).
    """
    labels: list[str] = []
    i = offset
    while True:
        if i >= len(data):
            raise ValueError("truncated wire-format name")
        length = data[i]
        i += 1
        if length == 0:
            break
        labels.append(data[i : i + length].decode("ascii"))
        i += length
    return ".".join(labels) + ".", i


def _ensure_trailing_dot(name: str) -> str:
    return name if name.endswith(".") else f"{name}."


def _longest_matching_apex(owner: str, sorted_apexes: list[str]) -> str | None:
    for apex in sorted_apexes:
        if owner == apex or owner.endswith(f".{apex}"):
            return apex
    return None


def _optional_ttl(fields: list[str], index: int) -> int | None:
    if len(fields) > index and fields[index]:
        return int(fields[index])
    return None


def _parse_a(fields: list[str]) -> ParsedRecord:
    if len(fields) < 2:
        raise ValueError(f"'+' (A) line needs fqdn:ip, got {fields!r}")
    fqdn, ip = fields[0], fields[1]
    return ParsedRecord(owner=fqdn, rtype="a", content=ip, ttl=_optional_ttl(fields, 2))


def _parse_a_and_ptr(fields: list[str]) -> list[ParsedRecord]:
    if len(fields) < 2:
        raise ValueError(f"'=' (A+PTR) line needs fqdn:ip, got {fields!r}")
    fqdn, ip = fields[0], fields[1]
    ttl = _optional_ttl(fields, 2)
    ptr_owner = _reverse_dns_owner(ip)
    return [
        ParsedRecord(owner=fqdn, rtype="a", content=ip, ttl=ttl),
        ParsedRecord(owner=ptr_owner, rtype="ptr", content=_ensure_trailing_dot(fqdn), ttl=ttl),
    ]


def _parse_cname(fields: list[str]) -> ParsedRecord:
    if len(fields) < 2:
        raise ValueError(f"'C' (CNAME) line needs fqdn:target, got {fields!r}")
    fqdn, target = fields[0], fields[1]
    return ParsedRecord(owner=fqdn, rtype="cname", content=_ensure_trailing_dot(target), ttl=_optional_ttl(fields, 2))


def _parse_generic(fields: list[str]) -> ParsedRecord:
    if len(fields) < 3:
        raise ValueError(f"':' (generic) line needs fqdn:type:rdata, got {fields!r}")
    fqdn, rtype_num, rdata = fields[0], fields[1], fields[2]
    if rtype_num != GENERIC_SRV_TYPE:
        raise ValueError(f"unsupported generic record type {rtype_num!r} for {fqdn!r} (only SRV/33 is handled)")
    return ParsedRecord(owner=fqdn, rtype="srv", content=_decode_srv_rdata(rdata), ttl=_optional_ttl(fields, 3))


def _parse_line(line: str) -> list[ParsedRecord]:
    prefix, rest = line[0], line[1:]
    fields = rest.split(":")

    if prefix == "Z":
        return [_parse_soa(fields)]
    if prefix == "&":
        return _parse_ns(fields)
    if prefix == "=":
        return _parse_a_and_ptr(fields)
    if prefix == "+":
        return [_parse_a(fields)]
    if prefix == "'":
        return [_parse_txt(fields)]
    if prefix == "C":
        return [_parse_cname(fields)]
    if prefix == ":":
        return [_parse_generic(fields)]

    raise ValueError(f"unrecognized tinydns line type {prefix!r}")


def _parse_ns(fields: list[str]) -> list[ParsedRecord]:
    if len(fields) < 3:
        raise ValueError(f"'&' (NS) line needs fqdn:ip:x, got {fields!r}")
    fqdn, ip, nameserver = fields[0], fields[1], fields[2]
    if not nameserver:
        raise ValueError(f"'&' (NS) line for {fqdn!r} has no nameserver hostname")
    ttl = _optional_ttl(fields, 3)
    out = [ParsedRecord(owner=fqdn, rtype="ns", content=_ensure_trailing_dot(nameserver), ttl=ttl)]
    if ip:
        out.append(ParsedRecord(owner=nameserver, rtype="a", content=ip, ttl=ttl))
    return out


def _parse_soa(fields: list[str]) -> ParsedRecord:
    if len(fields) < 8:
        raise ValueError(f"'Z' (SOA) line needs fqdn:mname:rname:ser:ref:ret:exp:min, got {fields!r}")
    fqdn = fields[0]
    mname, rname = _ensure_trailing_dot(fields[1]), _ensure_trailing_dot(fields[2])
    ser, ref, ret, exp, minimum = fields[3], fields[4], fields[5], fields[6], fields[7]
    content = f"{mname} {rname} {ser} {ref} {ret} {exp} {minimum}"
    return ParsedRecord(owner=fqdn, rtype="soa", content=content, ttl=_optional_ttl(fields, 8))


def _parse_txt(fields: list[str]) -> ParsedRecord:
    if len(fields) < 2:
        raise ValueError(f"''' (TXT) line needs fqdn:text, got {fields!r}")
    fqdn, encoded = fields[0], fields[1]
    text = _decode_tinydns_escapes(encoded).decode("utf-8")
    # PowerDNS's TXT `content` always includes the surrounding quotes as
    # literal characters (confirmed by actually running a converted
    # record through a real pdns_server, per #108 -- dig served back
    # `"HOUSE.HCMA"`, not `HOUSE.HCMA`, for a record built from an
    # unquoted content string). Escape backslashes first, then quotes, so
    # an already-escaped backslash doesn't get double-escaped by the
    # quote pass.
    quoted = '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'
    return ParsedRecord(owner=fqdn, rtype="txt", content=quoted, ttl=_optional_ttl(fields, 2))


def _reverse_dns_owner(ipv4: str) -> str:
    octets = ipv4.split(".")
    if len(octets) != 4:
        raise ValueError(f"not a dotted-quad IPv4 address: {ipv4!r}")
    return ".".join(reversed(octets)) + ".in-addr.arpa"
